# What is Data PreProcessing?



1)Machine Learning algorithms are completely dependent on data because it is the most crucial aspect that makes model training possible. On the other hand, if we won’t be able to make sense out of that data, before feeding it to ML algorithms, a machine will be useless. In simple words, we always need to feed right data i.e. the data in correct scale, format and containing meaningful features, for the problem we want machine to solve.

2)In other way defined as the procedure that makes our dataset more appropriate for ML process.

# Why Data Pre-processing?

After selecting the raw data for ML training, the most important task is data pre-processing. In broad sense, data preprocessing will convert the selected data into a form we can work with or can feed to ML algorithms. We always need to preprocess our data so that it can be as per the expectation of machine learning algorithm.

# what do we do in Data PreProcessing?

1)Handling Null Values

2)Standardization

3)Handling categorical values

4)One-hot encoding

5)Multicollinearity

# 1)Handling Null Values

1)In any real world dataset there are always few null values. It doesn’t really matter whether it is a regression,classfication or any other kind of problem, no model can handle these NULL or NaN values on its own so we need to intervene.
2)There are various ways for us to handle this problem. The easiest way to solve this problem is by dropping the rows or columns that contain null values.

# 1a)Implementing dropna() method 

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
a=dataset.dropna(subset=['Age', 'Salary'])
a

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

# 1b)using Imputer method to fill the missing values

In [4]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(dataset.iloc[:, 1:3])
dataset.iloc[:, 1:3] = imputer.transform(dataset.iloc[:, 1:3])
dataset

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

# 2)Handling Categorical Values

# 2a)What is the need to  Handle Categorical Values?

Categorical Data is the data that generally takes a limited number of possible values. Also, the data in the category need 
not be numerical, it can be textual in nature. All machine learning models are some kind of mathematical model that need numbers to work with. This is one of the primary reasons we need to pre-process the categorical data before we can feed it to machine learning models.

# 2b)Ways to handle Categorical Data


# i)using map function

In [5]:
x1=dataset.iloc[:,0]
x1

0     France
1      Spain
2    Germany
3      Spain
4    Germany
5     France
6      Spain
7     France
8    Germany
9     France
Name: Country, dtype: object

In [6]:
mapp={'France':1,'Spain':2,'Germany':3}
x1=x1.map(mapp)
x1

0    1
1    2
2    3
3    2
4    3
5    1
6    2
7    1
8    3
9    1
Name: Country, dtype: int64

# ii)using label encoder

In [7]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
y=labelencoder_X.fit_transform(y)
print(X)
y

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])


# 3)One Hot Encoding

So in One-Hot Encoding what we essentially do is that we create ’n’ columns where n is the number of unique values that the nominal variable can take.
Ex — Here if color can take Blue,Green and White then we will just create three new columns namely — color_blue,color_green and color_white and if the color is green then the values of color_blue and color_white column will be 0 and value of color_green column will be 1 .
So out of the n columns only one column can have value = 1 and the rest all will have value = 0.

# Implementation of one hot encoding

In [9]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
X

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

# 4)Multicollinearity and its impact 

Multicollinearity occurs in our dataset when we have features which are strongly dependent on each other. Ex- In this case we have features like color_blue,color_green and color_white which are all dependent on each other and it can impact our model.

The easiest method to identify Multicollinearity is to just plot a pairplot and you can observe the relationships between different features. If you get a linear relationship between 2 features then they are strongly co-related with each other and there is multicollinearity in your dataset.

simple method to avoid this is just we have to drop the first coulmn in this case we will drop france.we can still recognize it by the informations of spain and germany if they are not active that mean it is germany.


In [10]:
X=X[:,1:]
X

array([[0.00000000e+00, 0.00000000e+00, 4.40000000e+01, 7.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 3.00000000e+01, 5.40000000e+04],
       [0.00000000e+00, 1.00000000e+00, 3.80000000e+01, 6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 4.00000000e+01, 6.37777778e+04],
       [0.00000000e+00, 0.00000000e+00, 3.50000000e+01, 5.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 3.87777778e+01, 5.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 4.80000000e+01, 7.90000000e+04],
       [1.00000000e+00, 0.00000000e+00, 5.00000000e+01, 8.30000000e+04],
       [0.00000000e+00, 0.00000000e+00, 3.70000000e+01, 6.70000000e+04]])

# 5)Standardization or Feature Scaling

 It is a step of Data Pre Processing which is applied to independent variables or features of data. It basically helps to     normalise the data within a particular range. Sometimes, it also helps in speeding up the calculations in an algorithm.

# Techniques in Standardization:

1)Normalization

2)Standardization

The two most discussed scaling methods are Normalization and Standardization. Normalization typically means rescales the values into a range of [0,1]. Standardization typically means rescales data to have a mean of 0 and a standard deviation of 1 (unit variance).


# 1)Standard Scaler

The StandardScaler assumes your data is normally distributed within each feature and will scale them such that the distribution is now centred around 0, with a standard deviation of 1.

The mean and standard deviation are calculated for the feature and then the feature is scaled based on:

xi–mean(x)/stdev(x)

In [26]:
dataset1= pd.read_csv('Position_Salaries.csv')
x1=dataset1.iloc[:,[1,2]].values
x1

array([[      1,   45000],
       [      2,   50000],
       [      3,   60000],
       [      4,   80000],
       [      5,  110000],
       [      6,  150000],
       [      7,  200000],
       [      8,  300000],
       [      9,  500000],
       [     10, 1000000]], dtype=int64)

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x1= sc.fit_transform(x1)
x1

array([[-1.5666989 , -0.72004253],
       [-1.21854359, -0.70243757],
       [-0.87038828, -0.66722767],
       [-0.52223297, -0.59680786],
       [-0.17407766, -0.49117815],
       [ 0.17407766, -0.35033854],
       [ 0.52223297, -0.17428902],
       [ 0.87038828,  0.17781001],
       [ 1.21854359,  0.88200808],
       [ 1.5666989 ,  2.64250325]])

# 2)Min Max Scaler

Min Max Scaler assumes that the values should be in the range 0-1
it is calculated.


xi=xi–min(x)/(max(x)-min(x))

In [31]:
from sklearn.preprocessing import MinMaxScaler
ds2=dataset1
x2=dataset1.iloc[:,[1,2]].values
x2

array([[      1,   45000],
       [      2,   50000],
       [      3,   60000],
       [      4,   80000],
       [      5,  110000],
       [      6,  150000],
       [      7,  200000],
       [      8,  300000],
       [      9,  500000],
       [     10, 1000000]], dtype=int64)

In [40]:
m=MinMaxScaler()
x2= m.fit_transform(x2)
x2

array([[0.        , 0.        ],
       [0.11111111, 0.0052356 ],
       [0.22222222, 0.01570681],
       [0.33333333, 0.03664921],
       [0.44444444, 0.06806283],
       [0.55555556, 0.10994764],
       [0.66666667, 0.16230366],
       [0.77777778, 0.26701571],
       [0.88888889, 0.47643979],
       [1.        , 1.        ]])

# 3)Normalization

In [37]:
ds3=dataset1
x3=dataset1.iloc[:,[1,2]].values
from sklearn.preprocessing import Normalizer

In [39]:
n=Normalizer()
x3= m.fit_transform(x3)
x3

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.        , 0.        ],
       [0.11111111, 0.0052356 ],
       [0.22222222, 0.01570681],
       [0.33333333, 0.03664921],
       [0.44444444, 0.06806283],
       [0.55555556, 0.10994764],
       [0.66666667, 0.16230366],
       [0.77777778, 0.26701571],
       [0.88888889, 0.47643979],
       [1.        , 1.        ]])